# Generated by Django 4.0.6 on 2022-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='blog.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
