# Generated by Django 4.0.6 on 2022-07-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_icon_post_tag_tag_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
    ]
