# Generated by Django 4.0.6 on 2022-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='demo_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='demo_js',
            field=models.TextField(blank=True, null=True),
        ),
    ]
