# Generated by Django 4.0.6 on 2022-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('P', 'Post'), ('E', 'Practise'), ('T', 'Terminology')], default='P', max_length=1),
        ),
    ]
