# Generated by Django 4.0.6 on 2022-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0003_remove_term_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
