# Generated by Django 4.0.6 on 2022-07-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_rename_practicecategory_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='practice_category',
        ),
        migrations.AlterModelTable(
            name='practice',
            table='practice',
        ),
        migrations.AlterModelTable(
            name='usersolution',
            table='practice_user_solution',
        ),
    ]
