# Generated by Django 4.0.6 on 2022-07-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_practice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='practice',
            table='practice_exercise',
        ),
    ]
