# Generated by Django 4.0.6 on 2022-07-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_practice_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='usersolution',
            name='practise',
        ),
        migrations.RemoveField(
            model_name='usersolution',
            name='user',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='UserSolution',
        ),
    ]
