# Generated by Django 4.0.6 on 2022-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_usersolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersolution',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
