# Generated by Django 4.0.6 on 2022-07-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='exersise',
            new_name='exercise',
        ),
    ]
