# Generated by Django 4.0.6 on 2022-07-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_rename_exersise_practice_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersolution',
            name='practise',
        ),
        migrations.RemoveField(
            model_name='usersolution',
            name='user',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='UserSolution',
        ),
    ]
