# Generated by Django 4.0.6 on 2022-07-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0012_category_category_type'),
        ('practice', '0014_remove_usersolution_practise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('related_posts', models.ManyToManyField(to='blog.post')),
            ],
            options={
                'db_table': 'practice_subject',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult')], default='M', max_length=1)),
                ('exercise', models.TextField()),
                ('solution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('practise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.practice')),
            ],
            options={
                'db_table': 'practice_exercise',
            },
        ),
    ]
