# Generated by Django 4.0.6 on 2022-07-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='exercise',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
