# Generated by Django 4.0.6 on 2022-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0016_remove_exercise_title_exercise_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
